### ISSUE TITLE
Replace CHE_EXTRA_VOLUME_MOUNT with CHE_WORKSPACE_VOLUME in 'Volume Mounts' documentation

### ISSUE THREAD

**Issue by ajaygm** [eclipse/che-docs#102]
Per https://github.com/eclipse/che/issues/3888#issuecomment-274988735 `CHE_EXTRA_VOLUME_MOUNT` has been replaced by `CHE_WORKSPACE_VOLUME`.

Need to update https://github.com/eclipse/che-docs/blob/master/src/main/_docs/workspace-administration/ws-volume-mounts.md accordingly.

@TylerJewell can you confirm if this is really a bug or I might have misunderstood your comment.

**Comment by TylerJewell** [comment]
Yes, @ajaygm - very good catch.  That entire documentation page is for 4.x line and would not work at all with the 5.0 line.  It should be updated to talk about the `che.env` file and the configuration of `CHE_WORKSPACE_VOLUME`.   @JamesDrummond - I am assigning this as a high priority bug because the docs are just wrong.

**Comment by bmicklea** [comment]
Docs are updated here: https://github.com/eclipse/che-docs/pull/103
