### ISSUE TITLE
Document steps on setting up a debugger

### ISSUE THREAD

**Issue by tolusha** [eclipse/che-docs#120]
* ws-agent
* ws-master
* ide

The content that we need to update would be located here:
https://github.com/eclipse/che/wiki/Development-Workflow#debugging

**Comment by tolusha** [comment]
@TylerJewell 
We some info in the doc.

How to debug ws-master:
https://github.com/eclipse/che-docs/blob/d3061f240a9e5b313a0716aae4481ed2d022bfdb/src/main/_docs/setup/setup-configuration.md

How to configure SDM:
https://github.com/eclipse/che-docs/blob/d86680b9645c301d093cbe2c3c7c563b70d9b1c0/src/main/_docs/write-che-ide-plugins/plugins-setup-che-workspace.md

Do we still need to put that on wiki?

**Comment by TylerJewell** [comment]
Thanks, @tolusha.  I think what we should do is:
1. In the setup-configuration page, leave this alone, but in the future I may remove some of the debugging comments because it's not appropriate for end users (it's really only che developers).

2. In the wiki, we should have the content that core Che committers need to know to debug what they are writing.  So in the debugging page, we should have three (can be short) sections:
a: Debugging Che server
b: Debugging Che agents in workspaces
c: Debugging Che IDE extensions (is this SDM only, or other tactics)/

We do not have to make these explanations very detailed, but just accurate.  We can assume that readers of the wiki are expert developers, so we don't have to provide visuals and graphics.  But we do have to explain how to set it up.

3. When I rewrite the IDE plugins section to hande assemblies, I'll update those docs about providing debugging mode for those people working on custom assemblies.

**Comment by tolusha** [comment]
@TylerJewell 
I've updated wiki https://github.com/eclipse/che/wiki/Development-Workflow#debugging

**Comment by TylerJewell** [comment]
I didn't know that our ws-agents are always run in debug mode.  Why is that?  Shouldn't we have ws-agents be without jpda mode by default and then have some mode of activation?

**Comment by TylerJewell** [comment]
@skabashnyuk @tolusha - please let me know thoughts on ws agent debugging.  But closing this issue as completed for now.

**Comment by tolusha** [comment]
@TylerJewell 
This is the case only in Che but not in Codenvy.

I stick to development mode by default due to:
* it is very convenient for development to be able to connect to ws-agent at any time
* there is no request from users to have this mode not by default
* additional property requires documentation and supporting

**Comment by TylerJewell** [comment]
I don't think these are good reasons.  Che is considered a production product.  We need this to be similar to codenvy where debugging is not on by default.

I consider this a type of bug and something we need to tackle
