### ISSUE TITLE
Make it clearer that JDK is required for agents to be used

### ISSUE THREAD

**Issue by davidwindell** [eclipse/che-docs#220]
https://github.com/eclipse/che/issues/4963#issuecomment-298013427

**Comment by bmicklea** [comment]
@davidwindell - in investigating further the issue you had was due to a bug. The correct behavior is that if a stack doesn't have Java in by definition we will add it so that the agents will work.

**Comment by davidwindell** [comment]
@bmicklea The comment from @eivantsov states that

`jdk is required for a workspace agent`

The docs don't state this https://eclipse.org/che/docs/devops/runtime-recipes/index.html#other-optional-dependencies so should be updated. 

Can you re-open?

**Comment by bmicklea** [comment]
That table should only include components that the user has to add to their stack themselves. That's not the case with the JRE needed by the agents - if we don't find it in the user's stack then we automatically add it.

In many cases people will use their production recipe in Che (it's one of the big benefits of Che) and if we make it seem that they need a JRE in their recipe to work with Che it may force people to unnecessarily add it to their production recipe, or not use their production recipe Che because they believe that they will have to change that recipe.

**Comment by davidwindell** [comment]
Right you are! :+1:
