### ISSUE TITLE
Provide installation guide for how to deploy Che on OpenShift running on Azure

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#435]
### Description 
We should be providing an installation guide for how to deploy Eclipse Che on OpenShift running on Azure. 

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/openshift-prerequisites

**Comment by bmicklea** [comment]
Is there something unique about OpenShift on Azure? Wouldn't it be more generally useful to provide guidance on the kind of storage that is most ideal for Che on any Kube distro and execution location? Obviously we can't be extremely detailed since there are so many hosting providers and Kube distros, but it seems like starting with something general would be the right first step.

**Comment by themr0c** [comment]
We are closing this issue as it is appearing outdated. 

https://www.eclipse.org/che/docs/che-7/installing-eclipse-che-on-microsoft-azure/
