### ISSUE TITLE
Add section about adding debugger support

### ISSUE THREAD

**Issue by tsmaeder** [eclipse/che-docs#719]
Add a section on how to add debugger support to che-theia to the "Che extensibility reference" topic as seen in Che 7 docs overview #712

**Comment by rkratky** [comment]
@tsmaeder, when some content is ready, it can be added to the prepared template file at https://github.com/eclipse/che-docs/blob/master/src/main/pages/che-7/end-user-guide/ref_debug-adapter-protocol.adoc

**Comment by tolusha** [comment]
I am a bit confused, https://github.com/eclipse/che-docs/issues/712 contains several similar sections:
* Adding support for a new debugger
* Debug Adapter Protocol

This issue is about adding support for a new debugger and has to be added into https://github.com/eclipse/che-docs/blob/ab/dap/src/main/pages/che-7/hands-on-guidance/proc_adding-support-for-a-new-debugger.adoc#L1
